const descricaoColuna = {
        nomprod: "Descrição",
        espprod: "Especificação",
        codfabr: "Código do Fabricante",
        cl1prod: "1ª Classe",
        cl2prod: "2ª Classe",
        cl3prod: "3ª Classe",
        cl4prod: "4ª Classe",
        depprod: "Departamento",
        tipprod: "Tipo de Produto",
        obsprod: "Observações",
        desresu: "Descrição resumida",
        fgedeci: "Decimais?",
        xyzprod: "XYZ",
        atuprod: "Atualização",
        cod_ipi: "IPI",
        cod_irr: "IRR",
        subfede: "Substituto Federal?",
        ncmprod: "NCM",
        imgprod: "Imagem",
        codregr: "Regra de Sugestão",
        filfabr: "Filial do Fabricante",
        negprod: "Negativado",
        tipipro: "Tipo do Item: Atividade Industrial, Comerciais e Serviços",
        genepro: "Gênero do Item de Mercadoria/Serviço",
        lisipro: "Lista da Lei complementar 116/03",
        ex_prod: "Código EX, conforme a TIPI",
        indprop: "Indicador de Propriedade/Posse do Produto",
        codprop: "Código do Participante Proprietário/Possuidor do Produto",
        filprop: "Filial do Participante Proprietário/Possuidor do Produto",
        endprop: "Código do Endereço do Participante Proprietário/Possuidor do Produto",
        ctnprod: "Conta: Código da Conta Contábil",
        cbccpro: "Código da Base de Cálculo do Crédito",
        recprod: "Código da Natureza da Receita",
        prociap: "Participar do Controle de Crédito do Ativo? 0:Não -1:Sim",
        prodepr: "Controlar Depreciação do Ativo? 0:Não -1:Sim",
        regr_sa: "Regra de tributação de Saída",
        regr_en: "Regra de tributação de Entrada",
        parfide: "Produto gera pontuação fidelidade? -1:Sim; 0:Não",
        escombo: "Produto é um combo? 0:Não; 1:Sim Imprimindo os Itens; 2:Sim Imprimindo a Descrição do combo",
        agrgrad: "Usar o produto para agrupar os itens de grade? -1:Sim; 0:Não",
        lismate: "Exibir lista das matérias-primas para ser lançado como ingrediente avilto? -1:Sim; 0:Não",
        ctnfatu: "Código da conta contábil de faturamento", 
        negunid: "Unidade de Negócios",
        divisa1: "Divisão 1",
        divisa2: "Divisão 2",
        divisa3: "Divisão 3",
        divisa4: "Divisão 4",
        divisa5: "Divisão 5",
        codidiv: "Item de Divisão",
        codisub: "Item de Sub-Divisão",
        unvgrad: "Unidade de Venda",
        uncgrad: "Unidade de Compra",
        estmini: "Estoque Mínimo",
        pesliqu: "Peso Líquido",
        pesbrut: "Peso Bruto",
        desmaxi: "Desconto Máximo",
        fatconv: "Fator de Conversão",
        obsgrad: "Observações",
        lo1grad: "1ª Localização",
        lo2grad: "2ª Localização",
        ptopedi: "Ponto de Pedido",
        fgecomi: "Comissionado?",
        refgrad: "Referência",
        gragrad: "Grade",
        filprod: "Filial do Produto",
        lucgrad: "Lucro",
        cfdgrad: "CFOP Dentro",
        cffgrad: "CFOP Fora",
        ncmgrad: "NCM",
        dtagrad: "Data do Cadastro",
        ctngrad: "Conta do Plano de Contas",
        md5grad: "Código MD5 Válido",
        codante: "Código do Sistema Anterior",
        metgrad: "Metragem do Produto",
        tipcomi: "Tipo de Comissão (1: Percentual, 2: Valor)",
        sercomp: "Usar Controle de Série na Compra?",
        diaprox: "Dias para Novo Atendimento",
        mkpgrad: "Valor Markup do Produto",
        exc_ncm: "Exceção Fiscal NCM",
        codcest: "Código Especificador da Substituição Tributária (CEST)",
        bcpicms: "Base de Cálculo do ICMS",
        bcpicst: "Base de Cálculo do ICMS-ST",
        usesite: "Enviar Venda Externa?",
        gtingra: "Código GTIN (Código de Barras) para NF-e",
        proanpc: "Código do Produto da ANP",
        proanpd: "Descrição do Produto da ANP",
        tmpgrad: "Tempo Gasto na Produção",
        paigrad: "Item Pai para Registro de Compra",
        itempai: "É Item Pai?",
        embgrad: "Embalagem do Produto",
        maxacre: "Acréscimo Máximo no Item",
        pglpgra: "Percentual de GLP",
        pgnngra: "Percentual de Gás Natural",
        estaten: "Estoque de Atenção",
        vpartgr: "Valor de Partida",
        ml_grad: "Plano do Mercado Livre",
        diasgra: "Dias de Garantia",
        tribuid: "Tributaliza ID",
        iterele: "Escala Relevante de Produção",
        itecnpj: "CNPJ do Fabricante",
        datvenc: "Data de Vencimento do Produto",
        diavenc: "Dias para Aviso de Vencimento",
        livreid: "Código Livre (Digitação do Produto ID)",
        cobenef: "Código do Benefício Fiscal",
        usegrad: "Usuário que Fez o Cadastro",
        purgrad: "Percentual de Pureza da Semente",
        gergrad: "Percentual de Germinação da Semente",
        metrage: "Informar Metragem (Altura e Comprimento)?",
        estomax: "Estoque Máximo",
        tzgrad: "Percentual da Tz (Semente)",
        grauuid: "ID Único",
        ml_cate: "Código da Categoria no Mercado Livre",
        ml_idpd: "ID do Produto no Mercado Livre",
        lo3grad: "Localização 3",
        vitrine: "Quantidade de Produtos na Vitrine",
        cfgbala: "Configuração na Balança (Etiqueta)",
        codanvi: "Código do Produto na Anvisa",
        motanvi: "Motivo de Isenção na Anvisa",
        preanvi: "Preço Máximo Consumidor (Anvisa)",
        multemp: "Multiplica Tempo de Produção pela Quantidade?",
        biograd: "Índice de Mistura do Biodiesel (%)",
        impcomb: "Indicador de Importação",
        ufocomb: "UF de Origem do Produtor ou Importador",
        pufcomb: "Percentual Originário da UF",
        deslivr: "Descrição Livre",
        idivi_1: "Item de Divisão 1",
        idivi_2: "Item de Divisão 2",
        idivi_3: "Item de Divisão 3",
        idivi_4: "Item de Divisão 4",
        idivi_5: "Item de Divisão 5",
        estiest: "Estoque",
        resiest: "Reserva",
        filesto: "Filial",
        precomp: "Último Preço de Compra",
        ultcust: "Último Custo de Compra",
        cusmedi: "Custo Médio Calculado na última compra",
        cuspond: "Custo Médio Ponderado Calculado na última compra",
        prevend: "Preço de Venda Varejo",
        preprom: "Preço de Venda Promoção",
        preatac: "Preço de Venda Atacado",
        proplan: "Plano da Promoção",
        prodtin: "Data Início da Promoção",
        prodtfi: "Data Final da Promoção",
        curvabc: "Classificação na Curva ABC",
        estnega: "Permitir Estoque Negativo na Venda",
        forlinh: "Produto Fora de Linha",
        codesto: "Código Sequencial",
        ajuprec: "Permite ajustar o preço do produto no ato da venda? -1:Sim; 0:Não",
        qtdatac: "Quantidade para assumir preço de Atacado",
        custefe: "Custo Efetivo do Produto",
        pr1esto: "Preço venda alternativo 1",
        pr2esto: "Preço venda alternativo 2",
        qtdpend: "Quantidade aguardando chegada. Compra realizada",
        estuuid: "ID Único",
        intrasi: "Estoque em Trânsito",
        chegaem: "Data prevista para chegada",
        vlrcomp: "Preço pago pela compra",
        qtdprom: "Quantidade em promoção",
        vqtprom: "Valida quantidade em promoção? -1:Sim; 0:Não",
        lo1esto: "Local estoque 1",
        lo2esto: "Local estoque 2",
        lo3esto: "Local estoque 3",
        obsprom: "Observação sobre a promoção",
        qtdata2: "Quantidade para Atacado 2",
        preata2: "Preço de Atacado 2",
        giroest: "Percentual de Giro do Estoque",
        nomparc: "Nome do Parceiro/Razão Social",
      sobparc: "Sobrenome/Nome Fantasia",
      cnpparc: "CPF / CNPJ",
      regparc: "Registro Geral - RG",
      nasparc: "Data de Nascimento",
      cadparc: "Data de Cadastro",
      altparc: "Data da Última Alteração",
      obsparc: "Observações",
      homparc: "Home Page",
      emaparc: "E-mail",
      venpref: "Vendedor Preferencial",
      plapref: "Plano de Venda Preferencial",
      cobpref: "Portador Preferencial",
      spccons: "Data da Consulta SPC",
      negparc: "Data de Negativação",
      ultcont: "Último Contato",
      ultvend: "Última Venda",
      filaval: "Filial do Avalista",
      codaval: "Código do Avalista",
      limcred: "Limite de Crédito",
      doctipo: "Tipo de Documento",
      estcivi: "Estado Civil",
      sexparc: "Sexo",
      pesparc: "Tipo de Pessoa",
      codocup: "Ocupação",
      nacparc: "Nacionalidade",
      natparc: "Naturalidade",
      ctpparc: "Carteira Profissional",
      cnhparc: "Número da CNH",
      cat_cnh: "Categoria da CNH",
      supparc: "Superior",
      admparc: "Data de Admissão",
      demparc: "Data de Demissão",
      nomempr: "Nome da Empresa",
      endempr: "Endereço",
      comempr: "Complemento",
      dddempr: "Código de Área da Empresa",
      fonempr: "Telefone da Empresa",
      antempr: "Empresa do Emprego Anterior",
      ctpseri: "Série Carteira Profissional",
      fgeparc: "Ativo?",
      filconj: "Filial Cônjuge",
      codconj: "Código do Cônjuge",
      nomconj: "Nome do Cônjuge",
      cnpconj: "CPF do Cônjuge",
      nasconj: "Nascimento do Cônjuge",
      emaconj: "E-mail do Cônjuge",
      ddfconj: "DDD do Telefone",
      fonconj: "Telefone do Cônjuge",
      ddcconj: "DDD do Celular",
      celconj: "Nº Celular Cônjuge",
      porempr: "Porte da Empresa",
      tipempr: "Tipo de Empresa",
      ultende: "Último Endereço",
      renparc: "Renda Mensal",
      motbloq: "Motivo do Bloqueio",
      rntparc: "RNTRC - Registro Nacional de Transportadores Rodoviários de Carga",
      tacparc: "Trabalhador autônomo de cargas (informação de transportadora): 0=TAC Agregado; 1=TAC Independente; 2=Outros.",
      tpaparc: "Classificação do Nível do Parceiro",
      ucbparc: "Cobrador",
      datconj: "Data de Casamento",
      codrfid: "Código RFID",
      cnhvali: "Validade da Carteira de Motorista",
      obsconj: "Observações sobre o Cônjuge",
      undparc: "Unidade de Negócio",
      co_fina: "Consumidor Final?",
      obsfina: "Observações Financeiras",
      agenseg: "Agendamento para Segunda? 0:Não; -1:Sim;",
      agenter: "Agendamento para Terça? 0:Não; -1:Sim;",
      agenqua: "Agendamento para Quarta? 0:Não; -1:Sim;",
      agenqui: "Agendamento para Quinta? 0:Não; -1:Sim;",
      agensex: "Agendamento para Sexta? 0:Não; -1:Sim;",
      agensab: "Agendamento para Sábado? 0:Não; -1:Sim;",
      agendom: "Agendamento para Domingo? 0:Não; -1:Sim;",
      usuparc: "Usuário que realizou o Cadastro",
      regprec: "Regra de preço a se aplicar",
      datbloq: "Data que a cobrança será bloqueada",
      indbloq: "Bloqueio de cobrança por tempo indeterminado: 1=Sim, 0=Não",
      senparc: "Senha de Acesso Web",
      pisparc: "PIS do parceiro",
      codhora: "Código dos Horários",
      filante: "Filial do Sistema Anterior",
      paiparc: "Nome do Pai",
      maeparc: "Nome da Mãe",
      rotparc: "Deletar depois... Rever logs",
      falparc: "Cliente Falecido? 0:Não; -1:Sim",
      comfale: "Falecimento comunicado por",
      oriparc: "Origem do parceiro (dom_ori)",
      coddeli: "Código do Delivery",
      update_at: "Data e hora do último update",
      ctaclie: "Conta padrão cliente",
      ctaforn: "Conta padrão fornecedor",
      custpad: "Centro de Custo Padrão",
      logcadw: "Nome do usuário ou identificação do perfil do vendedor no site do intermediador",
      fgelgpd: "Autoriza o uso dos dados pessoais? -1:Sim; 0:Não",
      percomi: "Percentual de Comissão Padrão",
      dia_lib: "Controle de Dias para Liberação - D.U.TS",
      salbase: "Salário base do Funcionário",
      inssali: "Alíquota de INSS do Funcionário",
      fgtsali: "Alíquota de FGTS do Funcionário",
      irrfali: "Alíquota de IRRF do Funcionário",
      fonende: "Telefone",
      cgcende: "CPF / CNPJ",
      ieende: "RG / IE",
      endende: "Endereço",
      baiende: "Bairro",
      codcida: "Código da Cidade",
      cepende: "Cep",
      numende: "Numero",
      nomende: "Nome do Endereço",
      filparc: "Filial",
      faxende: "Fax",
      celende: "Celular",
      ddd_fon: "Código de Área Telefone",
      complem: "Complemento",
      referen: "Ponto de Referência",
      tiplogr: "Tipo de Logradouro",
      nommuni: "Município",
      uf_ende: "Estado",
      paiende: "País",
      ordende: "Ordem",
      iesende: "Insc. Estadual Substituto",
      sufende: "Inscrição na SUFRAMA",
      optsimp: "Optante Simples Nacional?",
      im_ende: "Insc. Municipal",
      ctbicms: "Contribuinte de ICMS?",
      cnaeend: "CNAE",
      tpeende: "Tipo do Endereço",
      ip_ende: "Instituição Pública?",
      pe_ende: "Preponderante Exportador?",
      ireende: "Registro de Exportador ",
      gpslong: "Posição GPS: Longitude",
      gpslati: "Posição GPS: Latitude",
      asfende: "Km total de Asfalto",
      estende: "Km total de Estrada de Chão",
      entende: "Itinerário",
      seqende: "Sequencial Primário",
      nom_end: "Nome do Endereço",
      iiedest: "Identificador do IE Destinatário NF-e/NFC-e 1:Contribuinte; 2:Isento; 9:Não Contribuinte",
      regimet: "Regime Tributário: 0:Não Informado; 1:Real; 2:Presumido; 3:Simples; 4:MEI",
      codtaen: "Código da Taxa de Entrega Padrão",
      fgeende: "Endereço desativado: -1:Sim; 0:Não",
      idendpw: "Id do Endereço do Pedido Web Food",
      azulzon: "Cliente Zona Azul? -1: Sim; 0:Não"

      };



export default descricaoColuna;